version: "3.9"
services:
  frontend:
    container_name: ecs-next
    build:
      dockerfile: Dockerfile
      context: .
      args:
        app: frontend
    command: pnpm start
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
